export interface FilterPreset {
  id: string;
  name: string;
  nameKo: string;
  nameJa: string;
  nameZh: string;
  /** RGBA overlay color */
  overlay: string;
  /** 0-1 overlay opacity */
  overlayOpacity: number;
  /** brightness multiplier: 1 = normal */
  brightness: number;
  /** contrast multiplier: 1 = normal */
  contrast: number;
  /** saturation multiplier: 1 = normal, 0 = grayscale */
  saturation: number;
  
  // Extended Professional Adjustments
  exposure: number;
  brilliance: number;
  highlights: number;
  shadows: number;
  warmth: number;
  tint: number;
  vignette: number;
  sharpness: number;
  vibrance: number;
  definition: number;
  blackPoint: number;
}

export interface FilterCategory {
  id: string;
  name: string;
  nameKo: string;
  nameJa: string;
  nameZh: string;
  icon: string;
  filters: FilterPreset[];
}

export const FILTER_CATEGORIES: FilterCategory[] = [
  {
    id: 'basic',
    name: 'Basic',
    nameKo: '기본',
    nameJa: '基本',
    nameZh: '基础',
    icon: '✨',
    filters: [
      {
        id: 'original',
        name: 'Original',
        nameKo: '원본',
        nameJa: 'オリジナル',
        nameZh: '原图',
        overlay: 'transparent',
        overlayOpacity: 0,
        brightness: 1,
        contrast: 1,
        saturation: 1,
        exposure: 1,
        brilliance: 0,
        highlights: 0,
        shadows: 0,
        warmth: 1,
        tint: 0,
        vignette: 0,
        sharpness: 0,
        vibrance: 1,
        definition: 0,
        blackPoint: 1,
      },
      {
        id: 'vivid',
        name: 'Vivid',
        nameKo: '비비드',
        nameJa: 'ビ비ッド',
        nameZh: '鲜艳',
        overlay: 'rgba(255, 100, 50, 0.05)',
        overlayOpacity: 0.05,
        brightness: 1.05,
        contrast: 1.15,
        saturation: 1.25,
        exposure: 1.05,
        brilliance: 0.15,
        highlights: 0.1,
        shadows: 0.05,
        warmth: 1.05,
        tint: 0,
        vignette: 0,
        sharpness: 0.2,
        vibrance: 1.3,
        definition: 0.1,
        blackPoint: 1.05,
      },
      {
        id: 'soft',
        name: 'Soft',
        nameKo: '소프트',
        nameJa: 'ソフト',
        nameZh: '柔和',
        overlay: 'rgba(255, 230, 220, 0.1)',
        overlayOpacity: 0.1,
        brightness: 1.08,
        contrast: 0.85,
        saturation: 0.9,
        exposure: 1.1,
        brilliance: -0.1,
        highlights: -0.2,
        shadows: 0.15,
        warmth: 1.02,
        tint: 0,
        vignette: 0,
        sharpness: 0,
        vibrance: 0.95,
        definition: -0.1,
        blackPoint: 0.95,
      },
      {
        id: 'sharp',
        name: 'Sharp',
        nameKo: '선명한',
        nameJa: 'シャープ',
        nameZh: '锐利',
        overlay: 'transparent',
        overlayOpacity: 0,
        brightness: 1.0,
        contrast: 1.25,
        saturation: 1.1,
        exposure: 1.0,
        brilliance: 0.1,
        highlights: 0.05,
        shadows: -0.05,
        warmth: 1.0,
        tint: 0,
        vignette: 0,
        sharpness: 0.5,
        vibrance: 1.1,
        definition: 0.3,
        blackPoint: 1.1,
      },
    ],
  },
  {
    id: 'mood',
    name: 'Mood',
    nameKo: '무드',
    nameJa: 'ムード',
    nameZh: '情调',
    icon: '🌙',
    filters: [
      {
        id: 'warm',
        name: 'Warm',
        nameKo: '따뜻한',
        nameJa: '暖かい',
        nameZh: '暖色',
        overlay: 'rgba(255, 165, 0, 0.15)',
        overlayOpacity: 0.15,
        brightness: 1,
        contrast: 1.05,
        saturation: 1.15,
        exposure: 1.0,
        brilliance: 0.1,
        highlights: 0.05,
        shadows: 0,
        warmth: 1.25,
        tint: 0,
        vignette: 0.1,
        sharpness: 0.1,
        vibrance: 1.2,
        definition: 0,
        blackPoint: 1.0,
      },
      {
        id: 'cool',
        name: 'Cool',
        nameKo: '쿨톤',
        nameJa: 'クール',
        nameZh: '冷色',
        overlay: 'rgba(0, 120, 255, 0.12)',
        overlayOpacity: 0.12,
        brightness: 1,
        contrast: 1.05,
        saturation: 0.9,
        exposure: 1.0,
        brilliance: 0.05,
        highlights: 0,
        shadows: -0.05,
        warmth: 0.75,
        tint: 0.1,
        vignette: 0,
        sharpness: 0.1,
        vibrance: 0.9,
        definition: 0,
        blackPoint: 0.95,
      },
      {
        id: 'dreamy',
        name: 'Dreamy',
        nameKo: '몽환',
        nameJa: 'ドリーミー',
        nameZh: '梦幻',
        overlay: 'rgba(200, 150, 255, 0.15)',
        overlayOpacity: 0.15,
        brightness: 1.08,
        contrast: 0.8,
        saturation: 0.8,
        exposure: 1.1,
        brilliance: -0.15,
        highlights: -0.2,
        shadows: 0.2,
        warmth: 1.0,
        tint: 0.1,
        vignette: 0.2,
        sharpness: 0,
        vibrance: 0.85,
        definition: -0.2,
        blackPoint: 0.9,
      },
      {
        id: 'cozy',
        name: 'Cozy',
        nameKo: '아늑한',
        nameJa: 'コージー',
        nameZh: '舒适',
        overlay: 'rgba(180, 120, 60, 0.15)',
        overlayOpacity: 0.15,
        brightness: 0.98,
        contrast: 0.95,
        saturation: 1.05,
        exposure: 0.98,
        brilliance: 0,
        highlights: -0.1,
        shadows: 0.1,
        warmth: 1.15,
        tint: 0,
        vignette: 0.15,
        sharpness: 0.1,
        vibrance: 1.1,
        definition: 0.1,
        blackPoint: 1.0,
      },
    ],
  },
  {
    id: 'nature',
    name: 'Nature',
    nameKo: '자연',
    nameJa: '自然',
    nameZh: '自然',
    icon: '🌿',
    filters: [
      {
        id: 'sunset',
        name: 'Sunset',
        nameKo: '석양',
        nameJa: '夕焼け',
        nameZh: '日落',
        overlay: 'rgba(255, 100, 50, 0.18)',
        overlayOpacity: 0.18,
        brightness: 1,
        contrast: 1.1,
        saturation: 1.25,
        exposure: 1.02,
        brilliance: 0.2,
        highlights: 0.15,
        shadows: 0.05,
        warmth: 1.3,
        tint: -0.1,
        vignette: 0.2,
        sharpness: 0.2,
        vibrance: 1.4,
        definition: 0.1,
        blackPoint: 1.1,
      },
      {
        id: 'ocean',
        name: 'Ocean',
        nameKo: '바다',
        nameJa: 'オーシャン',
        nameZh: '海洋',
        overlay: 'rgba(0, 200, 200, 0.12)',
        overlayOpacity: 0.12,
        brightness: 1,
        contrast: 1.08,
        saturation: 1.15,
        exposure: 1.05,
        brilliance: 0.1,
        highlights: 0.1,
        shadows: -0.05,
        warmth: 0.8,
        tint: 0,
        vignette: 0,
        sharpness: 0.3,
        vibrance: 1.25,
        definition: 0.2,
        blackPoint: 0.95,
      },
      {
        id: 'forest',
        name: 'Forest',
        nameKo: '숲',
        nameJa: 'フォレスト',
        nameZh: '森林',
        overlay: 'rgba(34, 139, 34, 0.12)',
        overlayOpacity: 0.12,
        brightness: 0.95,
        contrast: 1.15,
        saturation: 1.2,
        exposure: 0.95,
        brilliance: 0.1,
        highlights: -0.05,
        shadows: 0.1,
        warmth: 1.1,
        tint: -0.2,
        vignette: 0.1,
        sharpness: 0.4,
        vibrance: 1.3,
        definition: 0.3,
        blackPoint: 1.15,
      },
    ],
  },
  {
    id: 'retro',
    name: 'Retro',
    nameKo: '레트로',
    nameJa: 'レ트로',
    nameZh: '复古',
    icon: '📷',
    filters: [
      {
        id: 'vintage',
        name: 'Vintage',
        nameKo: '빈티지',
        nameJa: 'ヴィンテージ',
        nameZh: '怀旧',
        overlay: 'rgba(200, 160, 90, 0.2)',
        overlayOpacity: 0.2,
        brightness: 0.92,
        contrast: 0.9,
        saturation: 0.7,
        exposure: 0.9,
        brilliance: -0.1,
        highlights: -0.2,
        shadows: 0.2,
        warmth: 1.15,
        tint: 0.1,
        vignette: 0.4,
        sharpness: 0.1,
        vibrance: 0.8,
        definition: -0.1,
        blackPoint: 0.85,
      },
      {
        id: 'film',
        name: 'Film',
        nameKo: '필름',
        nameJa: 'フィルム',
        nameZh: '电影',
        overlay: 'rgba(80, 100, 80, 0.1)',
        overlayOpacity: 0.1,
        brightness: 0.98,
        contrast: 1.2,
        saturation: 0.85,
        exposure: 0.98,
        brilliance: 0.05,
        highlights: 0.1,
        shadows: 0.05,
        warmth: 1.05,
        tint: -0.05,
        vignette: 0.2,
        sharpness: 0.3,
        vibrance: 1.0,
        definition: 0.2,
        blackPoint: 1.1,
      },
      {
        id: 'polaroid',
        name: 'Polaroid',
        nameKo: '폴라로이드',
        nameJa: 'ポラロイド',
        nameZh: '拍立得',
        overlay: 'rgba(255, 240, 200, 0.15)',
        overlayOpacity: 0.15,
        brightness: 1.05,
        contrast: 0.85,
        saturation: 0.8,
        exposure: 1.05,
        brilliance: -0.1,
        highlights: -0.1,
        shadows: 0.15,
        warmth: 1.1,
        tint: 0,
        vignette: 0.35,
        sharpness: 0.1,
        vibrance: 0.9,
        definition: -0.05,
        blackPoint: 0.95,
      },
    ],
  },
  {
    id: 'bnw',
    name: 'B&W',
    nameKo: '흑백',
    nameJa: '白黒',
    nameZh: '黑白',
    icon: '⚫',
    filters: [
      {
        id: 'bw',
        name: 'B&W',
        nameKo: '흑백',
        nameJa: 'モノクロ',
        nameZh: '黑白',
        overlay: 'transparent',
        overlayOpacity: 0,
        brightness: 1.0,
        contrast: 1.3,
        saturation: 0,
        exposure: 1.02,
        brilliance: 0.2,
        highlights: 0.1,
        shadows: -0.05,
        warmth: 1.0,
        tint: 0,
        vignette: 0.15,
        sharpness: 0.4,
        vibrance: 1,
        definition: 0.2,
        blackPoint: 1.1,
      },
      {
        id: 'noir',
        name: 'Noir',
        nameKo: '느와르',
        nameJa: 'ノワール',
        nameZh: '黑色电影',
        overlay: 'rgba(0, 0, 30, 0.15)',
        overlayOpacity: 0.15,
        brightness: 0.8,
        contrast: 1.5,
        saturation: 0,
        exposure: 0.9,
        brilliance: 0.1,
        highlights: 0.2,
        shadows: -0.15,
        warmth: 0.9,
        tint: 0,
        vignette: 0.5,
        sharpness: 0.5,
        vibrance: 1,
        definition: 0.6,
        blackPoint: 1.4,
      },
    ],
  },
];

// Flat list of all filters (for compatibility)
export const FILTERS: FilterPreset[] = FILTER_CATEGORIES.flatMap((cat) => cat.filters);

export const ASPECT_RATIOS = [
  { id: 'free', label: 'Free', labelKo: '자유', labelJa: '自由', labelZh: '自由', ratio: null },
  { id: '1:1', label: '1:1', labelKo: '정방형 (1:1)', labelJa: '正方形 (1:1)', labelZh: '正方形 (1:1)', ratio: 1 },
  { id: '4:5', label: '4:5', labelKo: '인스타 (4:5)', labelJa: 'インスタ (4:5)', labelZh: '照片 (4:5)', ratio: 4 / 5 },
  { id: '9:16', label: '9:16', labelKo: '스토리 (9:16)', labelJa: 'ストーリー (9:16)', labelZh: '故事 (9:16)', ratio: 9 / 16 },
  { id: '16:9', label: '16:9', labelKo: '유튜브 (16:9)', labelJa: 'YouTube (16:9)', labelZh: '横屏 (16:9)', ratio: 16 / 9 },
  { id: '3:4', label: '3:4', labelKo: '3:4', labelJa: '3:4', labelZh: '3:4', ratio: 3 / 4 },
  { id: '4:3', label: '4:3', labelKo: '4:3', labelJa: '4:3', labelZh: '4:3', ratio: 4 / 3 },
];
